### ISSUE TITLE
Support kube2iam

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/issues#212]
https://kubernetes.slack.com/archives/C8149MREV/p1532461342000248

**Comment by tamalsaha** [comment]
cc: @zacharycarter 

https://github.com/kubedb/project/issues/210

**Comment by tamalsaha** [comment]
It is possible to pass annotations to pod and jobs as user chooses.

**Comment by shivpathak** [comment]
> It is possible to pass annotations to pod and jobs as user chooses. Fixed.

@tamalsaha Glad to know that there is feature to pass annotations.

But somehow it's not working to my snapshot JOB's pod.

i am using kube2iam to pass roles but it's not working - see following example yaml for mongodb - 

```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: test
  namespace: mongo
spec:
  version: "4.0.5-v1"
  storage:
    storageClassName: "gp2"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
  backupSchedule:
    podTemplate:
      metadata:
        annotations:
          iam.amazonaws.com/role: arn:aws:iam::xxxxxxx:role/test
    cronExpression: "@every 1m"
    s3:
      bucket: test
  terminationPolicy: Delete
```

**Comment by chrisghill** [comment]
@tamalsaha Can this be re-opened?  I don't think its technically fixed.

I see that you added podTemplate support for the snapshot, but the "Failed to generate osm secret" is still happening.  In our case we're trying to create Postgres snapshots into S3.  We use kube2iam and I've added the AWS role to the podTemplate like so:

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
...
  backupSchedule:
    cronExpression: "@every 5m"
    s3:
      bucket: bucket
      endpoint: 's3.amazonaws.com'
      prefix: flagr
    podTemplate:
      metadata:
        annotations:
          iam.amazonaws.com/role: <aws-iam-role>
```

We've verified the role gives access to the bucket, but we're still receiving:

```
Events:
  Type     Reason          Age   From             Message
  ----     ------          ----  ----             -------
  Warning  SnapshotFailed  5m1s  KubeDB operator  Failed to generate osm secret. Reason: AccessDenied: Access Denied
```

This failure happens immediately after the snapshot resource is created.  Importantly, it happens **before the snapshot job/pod is ever created**.  This seems to suggest that something else besides the actual snapshot job (the kubedb controller perhaps?) needs AWS S3 permissions as well.  I can see in the KubeDB docs (https://kubedb.com/docs/0.8.0-beta.2/concepts/snapshot/#aws-s3) that for S3 backups we're supposed to have a k8s secret with AWS key/secret but we'd prefer to use machine roles via kube2iam if possible.  However it appears to not be supported right now - is that correct?

Also, it appears this issue is directly related (but for Mongo instead of Postgres): https://github.com/kubedb/issues/issues/693

I can move this into its own separate issue if you prefer.
