### ISSUE TITLE
kubedb postgres restore from snapshot explicitly needs old secret

### ISSUE THREAD

**Issue by shivpathak** [kubedb/issues#637]
Hello,

I am new to kubedb operator, i tried to create postgres (in cluster) of course in K8S.

It works like charm. I further tried to explore snapshot backup to S3 which also works fine.

What I found not so nice is during restore from snapshot it explicitly requires old secret.

```
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: quick-postgres-restore
  namespace: demo
spec:
  version: "10.6-v2"
  storageType: Durable
  databaseSecret:
    secretName: quick-postgres-auth
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Pause
  init:
    snapshotSource:
      name: quick-postgres-snapshot
      namespace: demo
```

Why do we need the old secret in snapshot restore?

```
  databaseSecret:
    secretName: quick-postgres-auth
```

**Note** - Here I don't mean about dormant database restore that works nice, mine concern is here to restore snapshot from one K8S cluster to another K8S cluster.

**Comment by the-redback** [comment]
In restore process, the database password will be replaced with old database password (because of restore). So, as a result, if kubedb is not given the old password, many processes of kubedb will be broken such as snapshot, monitoring. 

So, we tried to add this as a prerequisite.

For a workaround, you can create a new secret with the old secret password data (ie, `POSTGRES_PASSWORD` and `POSTGRES_USER`). Then, use this secret name in `databaseSecret.secretName` field.

**Comment by shivpathak** [comment]
@the-redback Thanks for your response.

But I am still a bit confused, in snapshot we provide secret aws s3 secret not the postgres secret.

does snapshot use postgres secret behind the scene?

please find the instant snapshot config, there i provide only aws secret in field spec.storageSecretName

```
---
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: quick-postgres-snapshot
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: quick-postgres
  storageSecretName: postgres-snapshot-secret
  s3:
    endpoint: 's3.amazonaws.com'
    bucket: quick-postgres-snapshot
    prefix: dev
```
