### ISSUE TITLE
Postgresql version: "10.2-v2" not supporting WAL restore from backup (S3)

### ISSUE THREAD

**Issue by DandyDeveloper** [kubedb/issues#681]
During the restore.sh as part of the 10.2-v2 it uses the following: 

```
until wal-g backup-list &>/dev/null; do
  echo "waiting for archived backup..."
  sleep 5
done
```

If you provide an init from backup like so:

```
  init:
    postgresWAL:
      storageSecretName: pg-secret
      s3:
        bucket: backups
        prefix: 'path-to-folder'
```

It will create a environment variable with the following:

```
    - name: RESTORE_S3_PREFIX
      value: s3://backups/path-to-folder
```

This results in the following error:

>bash-4.4# wal-g backup-list
2019/11/08 07:51:24 FATAL: Did not set the following environment variables:
WALG_S3_PREFIX
WALG_FILE_PREFIX
WALG_GS_PREFIX

This error is not visible anywhere and the pod just infinitely waits and does nothing.

This is wrong as the newer versions of WALG expect the following: 

```
    - name: WALG_S3_PREFIX
      value: s3://backups/path-to-folder
```

**Comment by DandyDeveloper** [comment]
Sorry, I didn't realise this version had been deprecated. Closing.

**Comment by DandyDeveloper** [comment]
Nevermind, reopening, this is a problem in the latest versions as well.

**Comment by iamrz1** [comment]
Please provide your kubeDB operator version, postgres crd version, (10.2-v*), and yaml file so that we can reproduce this issue in our test environment.

Note: We use ARCHIVE_S3_PREFIX, and RESTORE_S3_PREFIX to set appropriate prefix (ie WALG_S3_PREFIX for s3). So it is not related to your issue.

**Comment by DandyDeveloper** [comment]
Thanks @iamrz1. Latest 0.13-rc for the kubedb version. 

With the following spec:

``` yaml
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-master
  namespace: kubedb
spec:
  version: "10.6-v3"
  storageType: Durable
  replicas: 3
  databaseSecret:
    secretName: pg-secret
  storage:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
        cpu: 100m
        memory: 2Gi
  configSource:
    configMap:
      name: pg-custom-config
  podTemplate:
    spec:
      nodeSelector:
        role: server
      env:
      - name: POSTGRES_DB
        value: database
      - name: POSTGRES_REPLICATION_MODE
        value: master
      - name: POSTGRES_REPLICATION_USER
        value: xxx
      - name: POSTGRES_REPLICATION_PASSWORD
        value: xxxxx
      - name: POSTGRES_MASTER_HOST
        value: xxxx
      - name: POSTGRES_MASTER_PORT_NUMBER
        value: "5432"
      - name: AWS_REGION
        value: us-east-1
      - name: MAX_WAL_SENDERS
        value: "50"
      - name: WAL_KEEP_SEGMENTS
        value: "300"
  init:
    postgresWAL:
      storageSecretName: pg-secret
      s3:
        bucket: bucket
        prefix: 'prefix/folder'
  terminationPolicy: WipeOut
```
