### ISSUE TITLE
Affinity/AntiAffinity support for MongoDB sharded cluster deployment

### ISSUE THREAD

**Issue by apu1111** [kubedb/issues#683]
Hi,
Currently configuring pod level affinity/antiAffinity has some issues due to the fact that every shard takes the same pod spec defined under shardTopology. Due to this, if pod affinity/anitiAffinity is configured, it is applied to all the pods across all the shards. Shard level affinity/antiAffinity support is needed based on unique label for each sharded replicaSet.

**Comment by tamalsaha** [comment]
Discussion Notes:

- https://github.com/kubedb/apimachinery/blob/722f0b216a672deab3b8e4fc91a08107722beb58/apis/kubedb/v1alpha1/mongodb_types.go#L221

- https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

StatefulSet specific affinity

Resource (cpu & memory)
Storage
PDB

ENV
Afinity
Toleration / Node Selector

preferredZones: []

**Comment by tamalsaha** [comment]
```
Use Template for Shard index in affinity rules

${SHARD_INDEX}

0
1
n-1


apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: kubedb.com/node.shard
              operator: In
              values:
              - mymongo-shard${SHARD_INDEX}
          topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: k8s.gcr.io/pause:2.0
```

**Future Extension Option**

Shard CRD

st-0
st-1
st-2


[]{
	st-0
	st-0
	st-0
	st-0
	st-1
	st-1
	st-1
	st-2
	st-2
	st-2
}
