### ISSUE TITLE
Postgres operator assigns random nodeports despite specifying exact ones

### ISSUE THREAD

**Issue by norbercik93** [kubedb/issues#712]
With following configuration services were assigned nodeports 32738 and 31047, despite providing  30050 and 30051

kubedb version v0.13.0-rc.0
```yaml
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
spec:
  version: "11.2"
  replicas: 2
  standbyMode: Hot
  streamingMode: asynchronous
  leaderElection:
    leaseDurationSeconds: 15
    renewDeadlineSeconds: 10
    retryPeriodSeconds: 2
  storageType: "Ephemeral"
  init:
    scriptSource:
      configMap:
        name: postgres-init-configmap
  podTemplate:
    metadata:
      annotations:
        passMe: ToDatabasePod
    controller:
      annotations:
        passMe: ToStatefulSet
    spec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: NodePort
      ports:
        - name:  http
          port:  5432
          nodePort: 30050
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: NodePort
      ports:
        - name:  http
          port:  5432
          nodePort: 30051
  updateStrategy:
    type: RollingUpdate
  terminationPolicy: "WipeOut"
```
