### ISSUE TITLE
No status on snapshot targeting Ceph s3 API

### ISSUE THREAD

**Issue by Amojow** [kubedb/issues#720]
**Overview of the issue** : 
I tried to save a MySQL snapshot in a S3 bucket hosted by Ceph. My snapshot is created and a request is sent to Ceph but this request is finishing only when i delete the Kubedb operator and my snapshot ressource have no status. 
```
NAME         DATABASENAME   STATUS      AGE
snap         bdd-test                   76m            
```

**How to reproduce :** 
Kubedb operator : v0.12.0, v0.13.0-rc.0 
Kubernetes v1.14
Ceph 13.2.6 mimic

Once my Mysql db is up, I create the secret with credentials and a snapshot with following config : 
```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: snap
  namespace: kubedb
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: bdd-test
  storageSecretName: secret-ceph
  s3:
    endpoint: "http://my-ceph:8080"
    bucket: "snapshots"
```

**What works and doesn't work ?** : 
 - I can't save my snapshots in a S3 Bucket on Ceph. The **request on Ceph is infinite**, doesn't send response, and ends only when i reload the kubedb operator. 
_The request in Ceph logs_  
```
2020-02-18 10:10:49.700 7fc247e6a700  1 ====== starting new request req=0x7fc247e63c80 =====
```
- I can save my snapshots in a Minio S3 Bucket. 

**What is the main problem ?** : 
The main problem is that there is **not any timeout** for the request made by Kubedb (to communicate with the S3 API of Ceph), and therefore **not any logs** on the situation of the **snapshot** in Kubdedb operator logs. The snapshot is then still with no status and can't be deleted (or you have to patch the finalizer manually). 

**Enhancement**
Handle an infinite request on S3 storage with a timeout.
