### ISSUE TITLE
elasticsearch heap size

### ISSUE THREAD

**Issue by Boolman** [kubedb/issues#728]
Im trying to configure the heapsize on elasticsearch, but without success.
Im running kubedb 0.12. according to the documentation this is done by setting the ES_JAVA_OPTS environment variable.  I've tried this and it doesnt change the xms and xmx values

```
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: "6.5.3"
  storageType: Durable
  podTemplate:
    spec:
      env:
      - name: ES_JAVA_OPTS
        value: "-Xms3072m -Xmx3072m"
      resources:
        requests:
          memory: "4Gi"
          cpu: 1
        limits:
          memory: "4Gi"
          cpu: 1
  databaseSecret:
    secretName: es-auth
  configSource:
    configMap:
      name: es-custom-config
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  terminationPolicy: Terminate
```
