### ISSUE TITLE
Connection to postgres is not protected by password

### ISSUE THREAD

**Issue by HNicolas** [kubedb/issues#729]
I just deployed a postgresql database to my cluster with the following object :
```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: my-app-postgres
  namespace: my-app
spec:
  version: "11.2"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  terminationPolicy: DoNotTerminate
  podTemplate:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: nodepool-name
      tolerations:
        - key: "key"
          operator: "Equal"
          value: "value"
```
The database pod is created, the corresponding secret is create with a `POSTGRES_PASSWORD` key. When I run `kubedb describe pg my-app-postgres` I see that that the password is defined.
The problem is that I can connect to my database with the `postgres` user without password or with any password...
Is this a known issue ?
