### ISSUE TITLE
APIServices operator are not available with 'FailedDiscoveryCheck'

### ISSUE THREAD

**Issue by janvdvegt** [kubedb/issues#733]
After installing KubeDB I'm getting errors, regardless of whether I'm using 0.12 or 0.13rc0:

`v1alpha1.mutators.kubedb.com` and `v1alpha1.validators.kubedb.com` are not available with `FailedDiscoveryCheck` as message. If we describe them, I get the message:

`failing or missing response from https://100.65.37.212:443/apis/mutators.kubedb.com/v1alpha1: Get https://100.65.37.212:443/apis/mutators.kubedb.com/v1alpha1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

When doing a generic `kubectl api-resources` it lists everything else and then errors:

`error: unable to retrieve the complete list of server APIs: mutators.kubedb.com/v1alpha1: the server is currently unable to handle the request, validators.kubedb.com/v1alpha1: the server is currently unable to handle the request`

When looking at the service, it correctly matches the deployment.

Kubernetes version (KOPS): 1.15.10
Helm version: 2.14.3 (but also fails with bash script)

There are a few other issues referring to this problem but the one fix mentioned (downgrading Helm) does not work and the others do not have a solution:

https://github.com/kubedb/issues/issues/574

What could be the reason? How can I solve this?

**Comment by virtuman** [comment]
have you had any luck getting this to work by any chance? or did you find any alternative to kubedb by any chance?
Thank you

**Comment by toonsevrin** [comment]
My mutators are also not able to connect to the api

**Comment by tamalsaha** [comment]
I tried to explain this error here:

https://github.com/kubedb/issues/issues/634#issuecomment-617360733

If the operator pod is running, this error should do away.

**Comment by toonsevrin** [comment]
My operator is running @tamalsaha, it even created the webhooks. But still:

The mutators APIService status:
```yaml
status:
  conditions:
    - lastTransitionTime: '2020-05-20T12:53:41Z'
      message: >-
        failing or missing response from
        https://10.42.53.211:443/apis/mutators.kubedb.com/v1alpha1: Get
        https://10.42.53.211:443/apis/mutators.kubedb.com/v1alpha1: write tcp
        192.168.123.6:38388->10.42.53.211:443: write: broken pipe
      reason: FailedDiscoveryCheck
      status: 'False'
      type: Available
```
