### ISSUE TITLE
Error trying to create a ElasticsearchVersions CRD 

### ISSUE THREAD

**Issue by cfitz** [kubedb/issues#737]
We are on version 0.12.0. 
When I try and add a CRD, I get and error:

The ElasticsearchVersion "6.2.4-v9" is invalid: spec.initContainer: Required value

I have tried the sample thats in the docs site: 

$ kubectl apply -f test.yaml

With test.yaml looking like:
```yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2.4-v9"
  labels:
    app: kubedb
spec:
  version: "6.2.4"
  deprecated: false
  db:
    image: "kubedb/elasticsearch:6.2.4-v1"
  exporter:
    image: "kubedb/elasticsearch_exporter:1.0.2"
  tools:
    image: "kubedb/elasticsearch-tools:6.2.4-v1"
  podSecurityPolicies:
    databasePolicyName: "elasticsearch-db"
    snapshotterPolicyName: "elasticsearch-snapshot"
```

**Comment by kamolhasan** [comment]
Since `v0.11.0`, `spec.initContainer` is a `required` field. You need to specify that in your YAML file.

```yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: "6.2.4-v9"
  labels:
    app: kubedb
spec:
  version: "6.2.4"
  deprecated: false
  db:
    image: "kubedb/elasticsearch:6.2.4-v1"
  exporter:
    image: "kubedb/elasticsearch_exporter:1.0.2"
  tools:
    image: "kubedb/elasticsearch-tools:6.2.4-v1"
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: "elasticsearch-db"
    snapshotterPolicyName: "elasticsearch-snapshot"
```

Sorry for the inconvenience, documentation will be updated soon.
