### ISSUE TITLE
kubedb/redis does not work with k8s 1.18

### ISSUE THREAD

**Issue by fjammes** [kubedb/issues#739]
I have this error message when installing redis on k8s 1.18 with kubedb:

```
kubectl apply -f manifest/redis-cluster.yaml
The Redis "redis-cluster" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`
```

Here is my yaml:
```
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster
  namespace: demo
spec:
  version: 4.0-v2
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Terminate 
  updateStrategy:
    type: RollingUpdate
```

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

kubedb version
Version = v0.13.0-rc.0
VersionStrategy = tag
GitTag = v0.13.0-rc.0
GitBranch = release-0.13
CommitHash = 9023600306c9c2fe67a2c1e6ac933bc43c24b3ff
CommitTimestamp = 2019-08-22T10:41:59
GoVersion = go1.12.9
Compiler = gcc
Platform = linux/amd64
