### ISSUE TITLE
Cannot create snapshot for postgreSQL on PV

### ISSUE THREAD

**Issue by ryojsb** [kubedb/issues#750]
I want take a snapshot for postgreSQL on PV of kubernetes.
However there is no documentation written about it.

I could take it on hostPath, but it's not the best for us.

I used a manifest below.

```
apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: local-snapshot-pv
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: quick-postgres
  local:
    mountPath: /repo
    persistentVolumeClaim:
      claimName: snapshot-pvc
```

**Comment by arslanhashmi** [comment]
@ryojsb you can add `snapshot-pvc` claim to your k8s cluster that this snapshot would point to.

Example PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-pvc
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hcloud-volumes
```
